### ISSUE TITLE
CSS Sourcemap paths

### ISSUE THREAD

**Issue by mantsch** [brocessing/kirby-webpack#20]
Hey, thanks for your great work. I got a little optimization request:
The CSS Sourcemap Reference in Chrome is the whole path like "/Users/Me/Sites/project-name/src/scss/common/_global.scss". 
So sometimes the important last part "/common/_global.scss" gets cutted out because of the long path name. Is it possible to get a shortened Version of the path?
Thank you.

**Comment by leoternoir** [comment]
Sorry for the delay !

Shortening the path is not our favorite workaround. I'm gonna check this problem soon.
