### ISSUE TITLE
semver check for kirby.config.json

### ISSUE THREAD

**Issue by bnomei** [brocessing/kirby-webpack#21]
would love to have a semver check in kirby.config.json like yarn.lock or package.json do. because auto updating a plugin might break things and without a proper way to fix that apart from removing the package from your kirby package manager and adding a version manually.

**Comment by arnaudjuracek** [comment]
We plan to soon release our **Kirby Package Manager** as its own [module](https://github.com/brocessing/kirby-package-manager), with a proper version managing.

The main problem being that the Kirby plugin community isn't (yet) really rigorous as of how a repo is standardised, and a lot of popular plugin does not have a `package.json`. A fallback to commit hash check might be possible in this case.

We'll keep you updated when the module is released.

**Comment by pqml** [comment]
Closing it for now as it will be a Kirby Package Manager feature
