### ISSUE TITLE
postcss.config.js: autoprefixer using browserlist in package.json

### ISSUE THREAD

**Issue by bnomei** [brocessing/kirby-webpack#22]
you could switch from object to array notation in postcss. this makes it easier to add other plugins  imho.
and use the (recommended) browserlist entry in package.json.

https://github.com/ai/browserslist#packagejson
https://github.com/postcss/autoprefixer#browsers

**package.json**
```json
...
  "browserslist": [
    "last 2 versions"
  ],
...
```

**postcss.config.js**
```js
module.exports = {
  plugins: [
    require('autoprefixer') // using browserlist
  ]
}
```

**Comment by leoternoir** [comment]
This is a design issue. Today, we centralize our postcss configuration in the `postcss.config.js` to be more flexible.

I get that this could be an issue when adding many postcss plugins. The browserlist option is nice tho, we could switch in the near future.

Closing the issue for now, but feel free to fork or pull request this repo!
