### ISSUE TITLE
eslint

### ISSUE THREAD

**Issue by bnomei** [brocessing/kirby-webpack#23]
you could provide a `eslintrc.js` file with this repo.

also there are *Gratuitous parentheses around expression: no-extra-parens* here...
https://github.com/brocessing/kirby-webpack/blob/master/scripts/webpack-build.js#L27
https://eslint.org/docs/2.0.0/rules/no-extra-parens

**Comment by arnaudjuracek** [comment]
There already is an `.eslintrc` provided with the repo.
As of the gratuitous parentheses, feel free to submit a PR.

**Comment by bnomei** [comment]
oh yes. my mistake. i lost all the hidden files using finder copy. 😓
