### ISSUE TITLE
compatibility with kirby-typography plugin

### ISSUE THREAD

**Issue by grommas** [brocessing/kirby-webpack#24]
First of all, thank you for this great boilerplate. The plugin kirby-typography doesn't seem to work inside kirby-webpack . Is there any fix or possible reason?

**Comment by pqml** [comment]
kirby-typography requires `mbstring` as PHP Extension. I'm not sure the built-in PHP Server provide it. 

You may need to use an external php server and use our `proxy` option in `main.config.js`
https://github.com/brocessing/kirby-webpack/blob/master/main.config.js#L36

**Comment by pqml** [comment]
I checked and mbstring is enabled on php built-in server >= 7.0

Could you provide a link to a not working project or give us more informations about your issue(s)?

**Comment by grommas** [comment]
it’s working, was my fault!
