### ISSUE TITLE
use a bundle entry multiple times

### ISSUE THREAD

**Issue by bnomei** [brocessing/kirby-webpack#25]
when creating a bundle entry in `main.config.js` it would be nice to be able use same file again and bundle it in multiple different output. like reusing `_fonts.css` in following example...

```js
const entries = {
  'src/main.js':     'www/assets/main.min.js',
  'src/_fonts.css':  'www/assets/a.css', // reuse. does not work (yet).
  'src/_a.css':      'www/assets/a.css',
  'src/_fonts.css':  'www/assets/b.css', // only last call will work.
  'src/_b.css':      'www/assets/b.css',
}
```

**Comment by arnaudjuracek** [comment]
I'm not sure I clearly understand your needs. Why not simply use CSS [@import](https://developer.mozilla.org/en-US/docs/Web/CSS/%40import) rule ?

**Comment by bnomei** [comment]
just did not expect it not to work so i reported it and provided a maybe too simplistic usecase. my bad. reusing an entry currently fails silently for all but the last call. maybe you could at least do something about that? 

other reasons... less http calls? sure that might be obsolete with http2 soon or when using a js loading lib. or when using `inline @import`-plugins with postcss.
in one case i wanted to reuse my components (5 out of 30 files) for a critical-css like file. so not fonts actually. but using a real critical-css extractor might be a better idea in the long run.

**Comment by pqml** [comment]
`import` in Sass / Less / Stylus compile and append the imported file's code into the main file. You also have options to use the same "inline import" behavior for basic css files. (there is a `inline` function in Less, and an `inline-css` opt in Stylus)

For more informations, see

- http://lesscss.org/features/#import-options

- http://sass-lang.com/guide#topic-5

- http://stylus-lang.com/docs/import.html

If you only have a post-css workflow without using a pre-processor, you can also use https://github.com/postcss/postcss-import

**Comment by bnomei** [comment]
i agree using `@import` properly is the best solution for my usecase.

but that does not solve the fact the reusing an entry does not work and fails silently (no merging happens).

**Comment by pqml** [comment]
It's not really a kirby webpack issue. You can't use the same key multiple time in a literal object in javascript.
