### ISSUE TITLE
recover from webpack error on browsersync refresh 

### ISSUE THREAD

**Issue by bnomei** [brocessing/kirby-webpack#26]
when an error is thrown by webpack compiler it would be nice to continue using dev server once the broken file (cs/js whatever) is changed – on browser sync event. currently one has to `ctrl-c` and `npm run dev` again.

**Comment by arnaudjuracek** [comment]
Can you provide an use case where the dev server stops when a broken file is changed ?

**Comment by bnomei** [comment]
i am using [tailwindcss](https://tailwindcss.com/) as a `postcss plugin`. when making a tying mistake (using an untility class not defined like `mx-E` instead of `mx-3`) and pressing save webpack fails and dev-server keeps displaying the error-overlay until i "reboot" it.

**Comment by pqml** [comment]
I have no problem to recover from an error with the basic kirby-webpack setup + tailwind ass postcss plugin. 

Could you provide us a full project causing your issue ?

**Comment by bnomei** [comment]
maybe i did set it up wrong... compiling files works fine.

**main.config.js**
```js
const entries = {
  'www/uipattern/_components.css': 'www/assets/components.css'
}

const css = {
  preprocessor: 'postcsss'
}
```

**webpack.config.common.js**
```js
const CSSLoaders = [
  {
    loader: 'css-loader',
    options: {
      url: !!(user.appEnv === 'development'),
      sourceMap: true,
      minimize: !!(user.appEnv === 'production')
    }
  },
  {
    loader: 'postcss-loader',
    options: {
      ident: 'postcss',
      plugins:  (loader) => [
        require('postcss-easy-import')(),
        require('precss')(),
        require('tailwindcss')('./www/uipattern/_tailwind.config.js'),
        require('autoprefixer')(),
        // require('cssnano')()
      ],
      sourceMap: true
    }
  }
]
```

**postcss.config.js**
```js
module.exports = { }
```

**www/uipattern/_components.css**
``` css
@import "./_tailwind-preflight.css";
@import "./_tailwind-utilities.css";
@import "./some-tailwind-postcss-component.css";
```

**www/uipattern/_tailwind-preflight.css**
```js
@tailwind preflight;
```
**www/uipattern/_tailwind-utilities.css**
```js
@tailwind utilities;
```
