### ISSUE TITLE
Browser sync reload when content changed not working.

### ISSUE THREAD

**Issue by illycz** [brocessing/kirby-webpack#30]
Kirby 2.5.8 (multilingual setup)
kirby-webpack 0.7.0

Error from console: `Uncaught SyntaxError: Unexpected identifier` in browser-sync-client.js?v=2.23.5:16

I'm using proxy...

Thanks

**Comment by pqml** [comment]
Hi, this error should be fixed on v7.0.1

https://github.com/brocessing/kirby-webpack/releases/tag/0.7.1

**Comment by pqml** [comment]
If you want to patch your current setup, just replace the first lines in `scripts/utils/browsersync-update-content.js`

```

**Comment by illycz** [comment]
Great!

What is the proper way to update kirby-webpack and not to lose changes like proxy settings etc.

Thanks

**Comment by pqml** [comment]
Sorry, just post the answer to your question :smile:

You only need to edit `scripts/utils/browsersync-update-content.js`
Change the first comment from `/* */` notation to `//` or just remove it

https://github.com/brocessing/kirby-webpack/issues/30#issuecomment-360160979
