### ISSUE TITLE
Hot reload issue with open panel

### ISSUE THREAD

**Issue by illycz** [brocessing/kirby-webpack#31]
I'm running dev server and my page is reloaded every 3second without any changes when I have also open panel.

Thanks

**Comment by pqml** [comment]
What's your setup? (plugins/fields/proxy url/protocol)

**Comment by illycz** [comment]
kirby.config:
```
{
  "modules": {
    "core": "https://github.com/getkirby/kirby.git",
    "panel": "https://github.com/getkirby/panel.git",
    "fields": {
      "tabs": "https://github.com/afbora/Kirby-Tabs-Field.git"
    },
    "plugins": {
      "google-analytics": "https://github.com/pedroborges/kirby-google-analytics.git",
      "images": "https://github.com/medienbaecker/kirby-images.git",
      "kirby-compress": "https://github.com/iksi/kirby-compress.git",
      "meta-tags": "https://github.com/pedroborges/kirby-meta-tags.git",
      "page-lock": "https://github.com/pedroborges/kirby-page-lock.git",
      "redirecty": "https://github.com/ivinteractive/kirbycms-redirects.git",
      "translations": "https://github.com/flokosiol/kirby-translations.git",
      "xml-sitemap": "https://github.com/pedroborges/kirby-xml-sitemap.git"
    },
    "tags": {},
    "widgets": {}
  }
}
```

I'm using proxy for kirby-webpack.local.
Anything else?

**Comment by pqml** [comment]
Thanks for your infos, I'll try to reproduce your issue with a similar environment.

One user already experienced a similar issue with the kirby shopkit plugin:
https://forum.getkirby.com/t/kirby-webpack-a-kirby-starter-kit-with-modern-frontend-tools/8695/14

For now, you can fix this by completely disabling reloading on content changes (reloading will continue to work for php / js / css edits):
https://forum.getkirby.com/t/kirby-webpack-a-kirby-starter-kit-with-modern-frontend-tools/8695/15

**Comment by pqml** [comment]
Okay, there is a bug with `page-lock` plugins.
I open a new issue for this
