### ISSUE TITLE
kirby-page-lock makes browsersync reloading again and again

### ISSUE THREAD

**Issue by pqml** [brocessing/kirby-webpack#32]

**Comment by illycz** [comment]
Maybe something with page-lock.interval: https://github.com/pedroborges/kirby-page-lock#page-lockinterval

**Comment by pqml** [comment]
[Fixed in v7.0.2.](https://github.com/brocessing/kirby-webpack/releases/tag/0.7.2)

I only changed two files, you can edit your project without recloning all the `kirby-webpack` repo.

All changes you need are on this commit: 
https://github.com/brocessing/kirby-webpack/commit/59c824fcf4251a301b08bc3e925a4ced5fdda974
