### ISSUE TITLE
Not receiving 404/Error page

### ISSUE THREAD

**Issue by cn-d** [brocessing/kirby-webpack#39]
When I navigate to a route or page that doesn't exist I get a 200 response - successfully receiving a blank page when I should be receiving a 404.

**Comment by EdwardLecock** [comment]
I don't think this related to kirby-webpack. Anyway you can add a 404 status header yourself.

```
c::set('headers', array(
	'error' => 404,
));
```

**Comment by cn-d** [comment]
Hi Edward,

Thanks for taking the time to reply. I thought so too but I tried it on a fresh clone and I have the same problem. Also, I have a website using an older version of kirby-webpack and the site works as expected. So I'm not sure how to diagnose the problem. Setting a 404 header and template didn't help. Do you have any other suggestions?

```
c::set('headers', array(
	'error' => 404,
));
```

**Comment by arnaudjuracek** [comment]
Did you try with a [`content/error/error.txt`](https://github.com/getkirby/plainkit/tree/master/content) page ?

**Comment by pqml** [comment]
Do you have an error page in your www/content folder ?
Like the one from the kirby plainkit: https://github.com/getkirby/plainkit/tree/master/content/error

I'll add one in the next release!

**Comment by cn-d** [comment]
I feel rather silly, that was indeed the problem. I forgot the whole premise of kirby.
