### ISSUE TITLE
kirby-next support

### ISSUE THREAD

**Issue by bnomei** [brocessing/kirby-webpack#41]
I am fooling around with [kirby next](https://getkirby.com/next) and your awsome kirby-webpack (version pre-release 0.8.0). this is what i did.

- got alpha-9 code from slack-channel/notion (kirby next Kirby 3 fellowship package required for access) and used these files (kirby, panel, content,...)
- needed to rename the plugin file from `kirby-webpack.php` to `index.php`
- and removed all **modules** from `kirby.config.json` to disable your *kirby plugin manager*

but i am stuck at getting browsersync to work. it gets loaded but does not use the hot-reload files but plain css/js files.

probably since i can not set the url in kirby next config (yet, since `c` helper class does not exist anymore). but maybe thats not necessary with kirby next's new server classes.

i hope you can give me a pointer how to solve this. thanks.

**Comment by pqml** [comment]
Hi, 

The url set in the config is really important for kirby-webpack to work, so it might be it

Currently none of us dispose of the Kirby 3 fellowship package and unfortunately we lack of time to try kirby-webpack with Kirby next.. We will surely work on this when kirby next will be released, but I think it will be better to do a full rewriting on another branch (with a proper `kpm` package for the plugin manager and the integration of the latest features of webpack 4)

I leave this issue open to anyone to contribute to!

**Comment by movingwater** [comment]
hi @bnomei
I just mangaged to get kirby3 running with this webpack plugin. Did everything you did and added the url in the config inside the if statement like this:

return [
    'url'  => ...
];

so now it works great.

**Comment by bnomei** [comment]
@movingwater thanks for letting me know.

**Comment by joernroeder** [comment]
@movingwater do you have your working version in a repo somewhere? i would love to play around with k-next and this as well :)

**Comment by movingwater** [comment]
Hi @joernroeder. Unforunatly I have just a private repo. But I think its really easy change the steps like @bnomei did. Then add the url in the config file like this:
```if (isset($_SERVER['HTTP_X_FORWARDED_FOR']) && $_SERVER['HTTP_X_FORWARDED_FOR'] === 'webpack') {
    return [
        'url' =>  $_SERVER['HTTP_X_FORWARDED_PROTO'] . '://' . $_SERVER['HTTP_X_FORWARDED_HOST'],
    ];
}```
I also excluded the core and panel modules in `kirby.config.json` so it doesn't update/add kirby 2. Then I just manually copied Kirby 3 in my www folder. Hope this does help?

**Comment by perpetualgrimace** [comment]
Will this be updated now that Kirby 3 is official out?

**Comment by arnaudjuracek** [comment]
> Will this be updated now that Kirby 3 is official out?

Yes it will.

**Comment by matthiasdeckx** [comment]
Trying to make this work with Kirby 3 but getting a 'Call to undefined function liveCSS()' error. Any tips?

**Comment by tststs** [comment]
@joernroeder here are the changes to migrate to Kirby 3.

https://github.com/tststs/kirby-webpack/commit/6d91ff5169b0727d41fc23d6b34e9607c03e8739

Feel free to cherry pick whatever you need.

**Comment by arnaudjuracek** [comment]
@tststs, @bnomei  I just created a [Kirby 3](https://github.com/brocessing/kirby-webpack/tree/kirby-3) branch partially based on your fork. Feel free to PR if you want to add things.

Once [properly tested](https://github.com/brocessing/kirby-webpack/pull/57), this branch will be merged in the main repository.
