### ISSUE TITLE
yarn 1.7

### ISSUE THREAD

**Issue by bnomei** [brocessing/kirby-webpack#42]
i did run into an issue with yarn after unboiling kirby-webpack 0.8.

https://github.com/yarnpkg/yarn/issues/5727#issuecomment-386108534

had to do this

```
rm yarn.lock
yarn install
```

**Comment by leoternoir** [comment]
Indeed we noticed issues with the `yarn.lock` file. 
Your workaround works fine for now, but we will release a lock-free version very soon.

**Comment by pqml** [comment]
`yarn.lock` / `package-lock.json` are now removed from the repo
