### ISSUE TITLE
dot in url

### ISSUE THREAD

**Issue by tasinttttttt** [brocessing/kirby-webpack#43]
I get a 404 when trying to access urls like `localhost:8080/foo.bar/`.

I've found some links about disabling the dot rule in the devserver [here](https://github.com/fabric8-ui/fabric8-ui/pull/1391/files) but I can't find information about how to implement this in the php server...

Any Ideas ?

**Comment by pqml** [comment]
The issue may comes from the PHP built-in server. It doesn't use apache and can't handle dots in url
(https://github.com/flokosiol/kirby-translations/issues/10#issuecomment-337919235)

You can use the proxy option in the `main.config.js` file to proxy a real php + apache local server

**Comment by pqml** [comment]
This is now supported in the new release
