### ISSUE TITLE
[PHP] Error: php is not a php binary

### ISSUE THREAD

**Issue by cn-d** [brocessing/kirby-webpack#44]
When I run `npm run start` I'm getting the following error and it's asking me to type in a 'Valid path or command for php'. 

> [PHP] Error: php is not a php binary
> [?] Valid path or command for php:

I believe this maybe be a consequence of running `brew upgrade node` for a problem in another project. How can I correct this problem? Any help would be greatly appreciated

**Comment by pqml** [comment]
what version of php do you use ? is the `php` cli working ?

**Comment by cn-d** [comment]
Running `php -v` I got the error

> dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.61.dylib
>   Referenced from: /usr/local/bin/php
>   Reason: image not found
> Abort trap: 6

So I the `php` cli is not working. I ran the command `brew list | xargs brew reinstall` and now all is fine, so the problem was with my environment - sorry, it was an unfamiliar error.
