### ISSUE TITLE
Module not found: Error: Can't resolve '@babel/runtime/helpers/classCallCheck'

### ISSUE THREAD

**Issue by geekance** [brocessing/kirby-webpack#51]
Looks like including modules is broken:
In InteractiveTitle.js I have:
class InteractiveTitle {
  constructor () {
  }
}
export default InteractiveTitle

in my index.js I try to include this module:
import InteractiveTitle from './js/objects/InteractiveTitle'

That leads to 
Module not found: Error: Can't resolve '@babel/runtime/helpers/classCallCheck'
Module not found: Error: Can't resolve '@babel/runtime/helpers/createClass'

**Comment by pqml** [comment]
I think it's fixed on the new release. I forget to include `@babel/runtime` as dependency on the previous release. You can fix it on your project via `npm i -S @babel/runtime`
