### ISSUE TITLE
Solution: How to use with Kirby 2.x, since Kirby 3 is out

### ISSUE THREAD

**Issue by monobasic** [brocessing/kirby-webpack#54]
Kirby's Repos have changed since the release of V3. The "legacy" v2 versions are now on: https://github.com/getkirby-v2

What most likely will happen: If you run '$yarn start' or `$npm run start` - Kirby and Panel will be updated to V3 and nothing will work any more :)

So, to use your existing Kirby 2 Setup with kirby-webpack, do the following:
1. Change the repo urls inside kirby.config.json:
`{
  "modules": {
    "core": "https://github.com/getkirby-v2/kirby.git",
    "panel": "https://github.com/getkirby-v2/panel.git",
.....`
2. Run either `$npm run kirby:update --force`, or if you use yarn `$yarn kirby:update --force`
3. Voilà! :)

**Comment by arnaudjuracek** [comment]
FIY, I just created a [Kirby 3](https://github.com/brocessing/kirby-webpack/tree/kirby-3) branch partially based on your fork. Feel free to PR if you want to add things.

Once [properly tested](https://github.com/brocessing/kirby-webpack/pull/57), this branch will be merged in the main repository. 

Once merge on master, Kirby-webpack for kirby 2 will still be available on a dedicated `kirby-2` branch.
