### ISSUE TITLE
How to adapt to Kirby 3 PHP routing

### ISSUE THREAD

**Issue by vitali-sigel** [brocessing/kirby-webpack#55]
👋
I am using kirby-webpack with Kirby CMS 3 now and it works great, but there is a problem with the development server.

- When i upload an image to the panel, the image does not show in the preview/thumbnail.
- I get this error when using the kirby-builder plugin
![kirby-builder-error-dev](https://user-images.githubusercontent.com/39295117/53891324-6d6a5500-402a-11e9-8e89-461bddbff864.png)

After the _npm run build_ process and starting the build in PHP server _php -S localhost:8000 **kirby/router.php**_ everything works. The images are there and even the plugin works.

So I tried to install the Kirby routing in the development server but failed.

`  phpServer = php({
    bin: user.devServer.phpBinary || 'php',
    host: user.devServer.phpHost || 'localhost',
    root: user.paths.www,
    verbose: false,
    promptBinary: true,
    args,
    router: user.paths.kirby.core + '/router.php' // Kirby routing 
  })`

Am i missing something here?
Thank you very much!

**Comment by pqml** [comment]
hi, unfortunately kirby-webpack does not support kirby 3 right now
The support is planned but I lack of time to make all the fixes and improvements for the migration

**Comment by vitali-sigel** [comment]
Okay, thanks for the fast reply!

**Comment by vitali-sigel** [comment]
I found a solution to this. In the release 0.9.1 you already implemented the path for the kirby router:
`
let args = [
    '-d', 'upload_max_filesize=100M',
    '-d', 'post_max_size=500M',
    '-d', 'short_open_tag=On',

    // enable custom php router
    // to handle routes with dots in it (like /default.json)
    // this is needed to use content representations
    path.join(user.paths.www, 'kirby', 'router.php')
  ]
`
I just had to adjust the folder from "site" to "kirby", since the router.php lives in the "kirby" folder.

Everything seems to work perfectly now!

**Comment by arnaudjuracek** [comment]
I'm glad that you fond a workaround ! 
Pinning this issue for later reference.

**Comment by arnaudjuracek** [comment]
FIY @grommas, I just created a [**Kirby 3 branch**](https://github.com/brocessing/kirby-webpack/tree/kirby-3) partially based on your fork. Feel free to PR if you want to add things.

Once [properly tested](https://github.com/brocessing/kirby-webpack/pull/57), this branch will be merged in the main repository.
