### ISSUE TITLE
mb_strpos(): Empty delimiter

### ISSUE THREAD

**Issue by DanielHirunrusme** [brocessing/kirby-webpack#60]
I'm having an issue trying to setup the kirby 3 branch from scratch. It works fine on mac, but on windows 10 I'm receiving the error below:

`mb_strpos(): Empty delimiter`

![kirby-error](https://user-images.githubusercontent.com/1197940/68718259-b2aa3380-0576-11ea-806c-b4557e6f719c.PNG)

**Comment by ffrancisco-rosa** [comment]
Hello. I am right now having this problem. Did you manage to solve this?

**Comment by pqml** [comment]
Hi, 

The php `mbstring` extension is needed by Kirby 3.

You can see other requirements here: 
https://getkirby.com/docs/guide/quickstart#requirements

**Comment by Luke-SF** [comment]
I have the mb_strpos function, yet when I run for example:

```
echo mb_strpos('a','b',0,'UTF-8');
```

it works, 

```
echo mb_strpos('a',null,0,'UTF-8');
PHP Warning:  mb_strpos(): Empty delimiter in php shell code on line 1
```

does not.
