### ISSUE TITLE
Can't update Kirby with npm script

### ISSUE THREAD

**Issue by chrtz** [brocessing/kirby-webpack#65]
`npm run kirby:update` won't work anymore.

```
🕛  [Kirby Updater] Nothing to update.
 ↪ unchanged https://github.com/getkirby/kirby.git
```

It still says I run Kirby 3.3.3, while 3.4.2 was released a few days ago.

**Comment by chrtz** [comment]
Still not working, while Kirby core has been updated to 3.4.3

```
➜  npm run kirby:update

> project kirby:update /Users/chrtz/Desktop/Desktop/project
> node scripts/kirby-update.js

🕛  [Kirby Updater] Nothing to update.
 ↪ unchanged https://github.com/getkirby/kirby.git
```

**Comment by Jorckx** [comment]
I'm running into the same problem… wondering if the new v3.6 is supported? I'm stuck with "3.5.7.1"

**Comment by arnaudjuracek** [comment]
All `npm run kirby:*` scripts are broken since Kirby 3.x, and will probably be removed in a potential next update.

With hindsight is wasn't the best idea, as [you should better use composer](https://getkirby.com/docs/cookbook/setup/composer).
