### ISSUE TITLE
Cant upload files through the panel - “None of the converters in the stack are operational”

### ISSUE THREAD

**Issue by isUnknown** [brocessing/kirby-webpack#66]
I'm not sure if this is related to kirby webpack but the fact is that I can’t upload files using the files field through the panel. It throws an error : “None of the converters in the stack are operational”.

<img width="1369" alt="e6cb4147703236e86a4dd4a64e6fdb7de0fb1f0f" src="https://user-images.githubusercontent.com/61452348/93327139-30377380-f81a-11ea-8e64-681677d8491c.png">

The files are correctly uploaded in the content>page folder but not in the media folder. In the panel, the field keeps being empty. In the text file (data), the array corresponding to the field is also empty.

**Comment by isUnknown** [comment]
Up.

Here is the error :
```
{
   "status":"error",
   "message":"Unauthenticated",
   "code":403,
    "exception":"Kirby\\Exception\\PermissionException",
    "key":"error.permission",
    "file":"\/kirby\/config\/api\/authentication.php",
    "line":11,"details":[],
    "route":"kirby-builder\/pages\/([a-zA-Z0-9\\.\\-_%= \\+\\@\\(\\)]+)\/fields\/([a-zA-Z0-9\\.\\-_%= \\+\\@\\(\\)]+)(?:\/(.*))?"
}
```

Here are lines 10, 11 and 12 in authentication.php : 
```
    if ($auth->type($allowImpersonation) === 'session' && $auth->csrf() === false) {
        throw new PermissionException('Unauthenticated');
    }
```

**Comment by antoine1000** [comment]
Hi,

Sorry for your error but it seems that it has nothing to do with Kirby Webpack...

Maybe check your PHP plugin are properly installed (like ImageMagick) and that you have the permission to upload files from the panel.

**Comment by isUnknown** [comment]
Ok, thanks for your answer.
