### ISSUE TITLE
php is not a php binary// macOS Big Sur

### ISSUE THREAD

**Issue by malteheitmueller** [brocessing/kirby-webpack#69]
hi!
Thanks for your great work. Just want to use it under macOS Big Sur but the php server could not start.
[1/3] Starting a php server...
[PHP] 💥  Error: php is not a php binary.

On macOS Catalina it works!

**Comment by perpetualgrimace** [comment]
In case anyone else winds up here first:

https://github.com/brocessing/kirby-webpack/issues/44#issuecomment-400116462

Big Sur no longer installs (and apparently removes) PHP. `brew install php` should help.

(Eventually, it did)
