### ISSUE TITLE
Is there a way to disable only the browser reload?

### ISSUE THREAD

**Issue by sigistardust** [brocessing/kirby-webpack#70]
Hello there,

When on the checkout page using the [Merx Plugin](https://github.com/wagnerwagner/merx), the browser keeps reloading infinitely. Maybe anyone knows where the problem may be, but for right now, it would be easier to just disable the automatic browser reload. Is there a way to do that?

**Comment by arnaudjuracek** [comment]
My guess is that Merx writes a file which triggers the reload.

Once you found the file, try adding its path to the [`devServer.ignored` array in main.config.js](https://github.com/brocessing/kirby-webpack/blob/master/main.config.js#L90-L91).
If you cannot find the culprit, you should be able to entirely disable the file watching feature by adding something like `'**/*'` to the same array.

**Comment by sigistardust** [comment]
Thank you, disabling it entirely worked.
